---
version: '3.4'

x-backend-app: &backend-app
  build:
    context: .
    dockerfile: Dockerfile
  restart: on-failure
  environment:
    RAILS_ENV: development
    NODE_ENV: development
    EDITOR: vim
  stdin_open: true
  user: "ruby"
  tty: true
  volumes:
    - .:/home/ruby/rails-app:rw
    - /home/ruby/rails-app/tmp/cache/bootsnap
    - /home/ruby/rails-app/vendor/bundle
    - /home/ruby/rails-app/storage

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  backend:
    <<: *backend-app
    entrypoint: ./docker-entrypoint.sh
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000/tcp
    depends_on:
      - postgres
